#!/usr/bin/env node
/**
 * graph-canon — render the SUPRA as a constellation you can SEE.
 *
 * Nobody understands 40 canons by reading 40 files. This generates a Mermaid map of
 * the canon spines + the relationships they DECLARE (the `Companion canons` / sibling
 * links in each header), grouped by domain, annotated with their ADOPT piece number.
 * Output: knowledge/SUPRA-MAP.md (GitHub renders the Mermaid block as a picture).
 *
 * Curated, not a hairball (practising piece #39 — legibility): edges are only the
 * relationships a canon EXPLICITLY declares in its header, deduped — not every passing
 * mention. Regenerate after adding/changing a canon: `node tools/graph-canon.mjs`.
 *
 * Usage:  node tools/graph-canon.mjs [--check]
 *   (no flag) write knowledge/SUPRA-MAP.md
 *   --check   regenerate in memory and exit 1 if it differs from the committed file
 *             (so CI can keep the map from going stale) — prints nothing on match.
 * Pure Node, zero deps.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const KNOW = join(ROOT, "knowledge");
const DIRS = ["ai-agents", "methodology", "architecture"];
const OUT = join(KNOW, "SUPRA-MAP.md");
const SPINE = /^(CANON-.*|VT-METHOD)\.md$/;

// ── collect spines ───────────────────────────────────────────────────────────
const spines = []; // { id, dir, title, headerRefs:Set }
for (const dir of DIRS) {
  const abs = join(KNOW, dir);
  if (!existsSync(abs)) continue;
  for (const f of readdirSync(abs)) {
    if (!SPINE.test(f)) continue;
    const id = f.replace(/\.md$/, "");
    const text = readFileSync(join(abs, f), "utf8");
    const lines = text.split(/\r?\n/);
    const title = (lines.find((l) => l.startsWith("# ")) || `# ${id}`).replace(/^#\s*/, "");
    // header block = up to the first "---" rule or first "## " section
    let header = "";
    for (const l of lines.slice(1)) {
      if (/^(---|## )/.test(l.trim())) break;
      header += l + "\n";
    }
    // every CANON-* / VT-METHOD token referenced in the header (the declared relationships)
    const refs = new Set();
    for (const m of header.matchAll(/\b(CANON-[A-Z0-9-]+|VT-METHOD)\b/g)) {
      const r = m[1].replace(/-+$/, "");
      if (r !== id) refs.add(r);
    }
    spines.push({ id, dir, title, refs });
  }
}
const ids = new Set(spines.map((s) => s.id));

// ── piece numbers from the ADOPT catalog ─────────────────────────────────────
const piece = new Map(); // canon id → piece number
const adopt = join(ROOT, "setup", "ADOPT-DEV-KIT.md");
if (existsSync(adopt)) {
  const a = readFileSync(adopt, "utf8");
  // split into piece sections; within each, the first Home CANON (same line) gets
  // THAT piece's number — never cross a section boundary (no wrong-number lies).
  for (const sec of a.split(/^###\s+/m)) {
    const numM = sec.match(/^([0-9]+[ab]?)\s*—/);
    if (!numM) continue;
    const homeM = sec.match(/\*\*Home:\*\*[^\n]*?(CANON-[A-Z0-9-]+|VT-METHOD)/);
    if (homeM) piece.set(homeM[1].replace(/-+$/, ""), numM[1]);
  }
}

// ── short, legible node labels ───────────────────────────────────────────────
const short = (id) => id.replace(/^CANON-/, "").replace(/-001$/, "").replaceAll("-", " ").toLowerCase();
const nodeId = (id) => id.replace(/[^A-Za-z0-9]/g, "_");
const label = (s) => {
  const p = piece.get(s.id);
  return `${p ? `#${p} ` : ""}${short(s.id)}`;
};

// ── edges: declared header refs, deduped (undirected) ────────────────────────
const edgeSet = new Set();
const edges = [];
for (const s of spines) {
  for (const r of s.refs) {
    if (!ids.has(r)) continue; // only edges between real spines
    const key = [s.id, r].sort().join("¦");
    if (edgeSet.has(key)) continue;
    edgeSet.add(key);
    edges.push([s.id, r]);
  }
}

// ── render Mermaid ───────────────────────────────────────────────────────────
const DIR_TITLE = { "ai-agents": "ai-agents (how agents work)", methodology: "methodology (how work is done)", architecture: "architecture (structure & inheritance)" };
let m = "```mermaid\nflowchart LR\n";
for (const dir of DIRS) {
  const inDir = spines.filter((s) => s.dir === dir);
  if (!inDir.length) continue;
  m += `  subgraph ${nodeId(dir)}["${DIR_TITLE[dir] || dir}"]\n`;
  for (const s of inDir) m += `    ${nodeId(s.id)}["${label(s)}"]\n`;
  m += "  end\n";
}
for (const [a, b] of edges) m += `  ${nodeId(a)} --- ${nodeId(b)}\n`;
m += "```\n";

const orphans = spines.filter((s) => !edges.some(([a, b]) => a === s.id || b === s.id));

const doc = `# SUPRA-MAP — the canon constellation (generated)

> **Generated by \`tools/graph-canon.mjs\` — do not edit by hand.** Regenerate after
> adding or changing a canon: \`node tools/graph-canon.mjs\`. Nodes are canon spines
> (labelled with their ADOPT piece number); edges are the **companion/sibling
> relationships each canon declares in its header** (curated, not every mention).
> ${spines.length} spines · ${edges.length} declared relationships.

${m}
**Legend.** \`#N\` = its piece in [\`setup/ADOPT-DEV-KIT.md\`](../setup/ADOPT-DEV-KIT.md).
Grouped by \`knowledge/\` domain. An edge = "these two canons explicitly reference each
other as companions/siblings" — the seams where one canon says *that concern is owned
there, not here*.${orphans.length ? `\n\n_Spines with no declared header relationship (standalone): ${orphans.map((s) => short(s.id)).join(" · ")}._` : ""}
`;

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current.trim() !== doc.trim()) {
    console.error("✗ SUPRA-MAP.md is stale — run `node tools/graph-canon.mjs` and commit.");
    process.exit(1);
  }
  process.exit(0);
}

writeFileSync(OUT, doc, "utf8");
console.log(`✓ wrote ${OUT.replace(ROOT, ".")} — ${spines.length} spines, ${edges.length} relationships`);
